name: fresco-deploy

#on:
#  push:
#    tags:
#      - '*'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        working-directory: deploy

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: deploy

      - name: Terraform Apply
        if: success()
        run: terraform apply -auto-approve tfplan
        working-directory: deploy

      - name: Terraform Output
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.0.0
          tf_actions_subcommand: 'output'
          tf_actions_working_dir: 'deploy'
        id: tf_output

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

      - name: Deploy to S3
        run: |
          # Extract S3 bucket name from Terraform output
          S3_BUCKET_NAME=$(echo '${{ steps.tf_output.outputs.stdout }}' | jq -r '.frontend_bucket_name.value')
          echo "Extracted S3 bucket name: $S3_BUCKET_NAME"
          
          # Check if S3_BUCKET_NAME is empty
          if [ -z "$S3_BUCKET_NAME" ]; then
            echo "Error: Failed to extract S3 bucket name"
            exit 1
          fi
          
          # Deploy to S3
          cd frontend
          aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete

      - name: Invalidate CloudFront
        run: |
          # Extract CloudFront Distribution ID from Terraform output
          DISTRIBUTION_ID=$(echo '${{ steps.tf_output.outputs.stdout }}' | jq -r '.cloudfront_distribution_id.value')
          echo "Extracted CloudFront Distribution ID: $DISTRIBUTION_ID"
          
          # Check if DISTRIBUTION_ID is empty
          if [ -z "$DISTRIBUTION_ID" ]; then
            echo "Error: Failed to extract CloudFront Distribution ID"
            exit 1
          fi
          
          # Invalidate CloudFront
          aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
