name: fresco-backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK (choose the appropriate version for your Scala project)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'  # You can also use 'temurin' or others

      # Cache SBT dependencies to speed up builds
      - name: Cache SBT
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-sbt-

      # Install sbt
      - name: Install SBT
        run: |
          curl -L https://github.com/sbt/sbt/releases/download/v1.5.5/sbt-1.5.5.tgz | tar xz
          sudo mv sbt /usr/local/bin/sbt

      # Run tests using SBT
      - name: Run Tests
        working-directory: backend
        run: |
          mv src/main/resources/application.conf.test src/main/resources/application.conf
          sbt test
